### ISSUE TITLE
Landscape printout wrongly rotated and cut off

### ISSUE THREAD

**Issue by pcdi** [mephitrpg/rpg-cards#185]
If a landscape orientation for the page size is selected, the cards are displayed correctly in the output, however the printout is wrong, as the page is turned again (see fig. 3).

Page size settings:
![Page size settings](https://github.com/crobi/rpg-cards/assets/4654151/bcc2fa81-b096-4937-b1b4-bf274c4dcec4)

Generated output:
![Output](https://github.com/crobi/rpg-cards/assets/4654151/9d9d8097-c3ef-43ca-b528-43c92c9f599d)

Page as seen in the browser print dialog:
![Print dialog](https://github.com/crobi/rpg-cards/assets/4654151/7260666a-71d9-481d-94ca-88f23fe74941)

The error seems to lie in this function:

https://github.com/crobi/rpg-cards/blob/e449f5559d9940df795bd21fc52ec6defbd293e3/generator/js/cards.js#L743-L755

For landscape printouts, `pw` and `ph` need to be switched around. You can test this by opening developer tools on the generated output and switching around the two values in `/html/body/div/style`:

Change

```css
@page {
    margin: 0;
    size:297mm 210mm;
    -webkit-print-color-adjust: exact;
}
```
to
```css
@page {
    margin: 0;
    size:210mm 297mm;
    -webkit-print-color-adjust: exact;
}
```
The generated output looks the same, but now the print preview shows the correct orientation.
